// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrgzSGjKHpQ_s1tplwm7MZpU97K65IteA',
    appId: '1:622422611048:web:9c9a9134565c4be39917dd',
    messagingSenderId: '622422611048',
    projectId: 'chatappflutter-fe28d',
    authDomain: 'chatappflutter-fe28d.firebaseapp.com',
    storageBucket: 'chatappflutter-fe28d.firebasestorage.app',
    measurementId: 'G-76MLR3T05F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftQMgsELIu_eh91z2iaWCaXeI8YGukwU',
    appId: '1:622422611048:android:a82b6f437424b6039917dd',
    messagingSenderId: '622422611048',
    projectId: 'chatappflutter-fe28d',
    storageBucket: 'chatappflutter-fe28d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZTDvOvq4tjtIl64dIB9WNA7OFMWTBZJk',
    appId: '1:622422611048:ios:0cbc6ce3e33d52259917dd',
    messagingSenderId: '622422611048',
    projectId: 'chatappflutter-fe28d',
    storageBucket: 'chatappflutter-fe28d.firebasestorage.app',
    iosClientId: '622422611048-idkuvthui1amu5cas891cjif6naddeuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTDvOvq4tjtIl64dIB9WNA7OFMWTBZJk',
    appId: '1:622422611048:ios:0cbc6ce3e33d52259917dd',
    messagingSenderId: '622422611048',
    projectId: 'chatappflutter-fe28d',
    storageBucket: 'chatappflutter-fe28d.firebasestorage.app',
    iosClientId: '622422611048-idkuvthui1amu5cas891cjif6naddeuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrgzSGjKHpQ_s1tplwm7MZpU97K65IteA',
    appId: '1:622422611048:web:c9c4d3861f5dd5199917dd',
    messagingSenderId: '622422611048',
    projectId: 'chatappflutter-fe28d',
    authDomain: 'chatappflutter-fe28d.firebaseapp.com',
    storageBucket: 'chatappflutter-fe28d.firebasestorage.app',
    measurementId: 'G-3YZ9E603S4',
  );

}